/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/common/card.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    Header: typeof import('./src/components/common/header.vue')['default']
    Login: typeof import('./src/components/auth/login.vue')['default']
    Machine_status: typeof import('./src/components/machine/machine_status.vue')['default']
    Machine_status_cpu: typeof import('./src/components/machine/machine_status_cpu.vue')['default']
    Minecraft_controller: typeof import('./src/components/minecraft/minecraft_controller.vue')['default']
    Minecraft_filemanager: typeof import('./src/components/minecraft/minecraft_filemanager.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NHeader: typeof import('naive-ui')['NHeader']
    NImage: typeof import('naive-ui')['NImage']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Template: typeof import('./src/components/common/template.vue')['default']
  }
}
