/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Class_admin_index: typeof import('./src/components/pages/class_admin/class_admin_index.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    Course_admin_assignment: typeof import('./src/components/pages/course_admin/course_admin_assignment.vue')['default']
    Course_admin_book_detail: typeof import('./src/components/pages/course_admin/course_admin_book_detail.vue')['default']
    Course_admin_books: typeof import('./src/components/pages/course_admin/course_admin_books.vue')['default']
    Course_admin_conservator: typeof import('./src/components/pages/course_admin/course_admin_conservator.vue')['default']
    Course_admin_course_details: typeof import('./src/components/pages/course_admin/course_admin_course_details.vue')['default']
    Course_admin_course_qdb: typeof import('./src/components/pages/course_admin/course_admin_course_qdb.vue')['default']
    Course_admin_index: typeof import('./src/components/pages/course_admin/course_admin_index.vue')['default']
    Course_admin_paper: typeof import('./src/components/pages/course_admin/course_admin_paper.vue')['default']
    Course_admin_topic_database: typeof import('./src/components/pages/course_admin/course_admin_topic_database.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    Exam_alert: typeof import('./src/components/common/exam_alert.vue')['default']
    Exam_card: typeof import('./src/components/common/exam_card.vue')['default']
    Exam_draw: typeof import('./src/components/common/exam_draw.vue')['default']
    Exam_header: typeof import('./src/components/common/exam_header.vue')['default']
    Exam_sider: typeof import('./src/components/common/exam_sider.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/auth/login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Student_index: typeof import('./src/components/pages/student/student_index.vue')['default']
    System_admin_index: typeof import('./src/components/pages/system_admin/system_admin_index.vue')['default']
    Template: typeof import('./src/components/common/template.vue')['default']
  }
}
